/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jackbox.editor.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void openJackBoxGame() {
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
